#!/bin/bash
#PBS -l nodes=1:ppn=20
#PBS -l walltime=01:00:00
#PBS -N myjob0
#PBS -o myjob1.out
#PBS -e myjob.err
#PBS -q workq
#PBS -A loni_cyen405
#PBS -m e
#PBS -M yli027@latech.edu

work="/home/yli027/lab2"
XFILE="lab2_1"
cd $work
./$XFILE
